### ISSUE TITLE
Export too?

### ISSUE THREAD

**Issue by j2l** [brotherlu/BPyAirfoil#5]
I'm generating NACA profiles and modifying them and would love to export to DAT for airfoiltools
Any plans?

**Comment by brotherlu** [comment]
Sadly no. I don't have the time to add features. I am only trying to keep it working in the latest Blender LTS.

**Comment by j2l** [comment]
And it works very well indeed :)
Thank you very much for it!

If only I could have [swiftBlock](https://github.com/tkeskita/swiftBlock/issues/7) to work ...
